name: Build Windows Debug

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Haxe
        uses: ./.github/actions/setup-haxe

      - name: haxelib
        run: |
          rm -rf D:\a\_temp/hxcpp_cache
          haxelib fixrepo --global

          haxelib install hxcpp
          haxelib install haxelib
          haxelib install crypto

          haxelib list

      - name: Build Windows
        run: |
          haxelib run lime build windows -release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug-build
          path: export/debug/windows/bin/
