name: Build Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Haxe + Haxelib
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Cache Haxelib
        uses: actions/cache@v4
        with:
          path: |
            export
            C:\haxelib
            C:\Users\runneradmin\.haxelib
          key: ${{ runner.os }}-haxelib-${{ hashFiles('**/.github/workflows/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-haxelib-

      - name: Install libs
        env:
          HAXEPATH: C:\hostedtoolcache\windows\haxe\4.3.6\x64
        run: |
          haxelib setup C:\haxelib
          
          git submodule update --init --recursive
          
          haxelib --global install hmm
          haxelib --global run hmm setup
          haxelib run hmm install

          haxelib install hxp 1.3.0
          
          haxelib remove lime
          haxelib remove openfl
          haxelib git lime https://github.com/FunkinCrew/lime
          haxelib git openfl https://github.com/FunkinCrew/openfl
          haxelib set lime git
          haxelib set openfl git

          haxelib run lime setup
          haxelib run lime rebuild windows
          
      - name: Build 
        env:
          HAXEPATH: C:\hostedtoolcache\windows\haxe\4.3.6\x64
        run: |
          echo $env:HAXEPATH
          haxelib list
          haxelib run lime build windows

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: export/release/windows/bin
